version: '3'
services:
  app:
    image: 'node:18'
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app:cached
    working_dir: /usr/src/app

  redis:
    image: 'redis:alpine'
    environment:
      - REDIS_PASSWORD
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
